version: '3'

services:
  city-quest:
    image: city-quest:0.0.1-SNAPSHOT
    restart: unless-stopped
    ports:
      - 8080:8080
      
   leaderboard:
    image: leaderboard:1.0-SNAPSHOT
    restart: unless-stopped
    ports:
      - 8081:8081