version: '3'

services:
  consul:
    image: consul
    restart: unless-stopped
    ports:
      - 8500:8500
  city-quest:
    image: city-quest:0.0.1-SNAPSHOT
    restart: unless-stopped
    ports:
      - 8080:8080
      
  leaderboard:
    image: leaderboard:0.0.1-SNAPSHOT
    restart: unless-stopped
    ports:
      - 8081:8081
